# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Alpha Build

on:
  push:
    branches: [alpha]
  pull_request:
    branches: [alpha]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno compile --unstable --allow-env --allow-run --allow-net --allow-read --allow-write --output build/lthn --target x86_64-unknown-linux-gnu src/server.ts
      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: build/lthn
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: latest-linux-amd64
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/lthn

  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno compile --unstable --allow-env --allow-run --allow-net --allow-read --allow-write --output build/lthn --target x86_64-pc-windows-msvc src/server.ts
      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: build/lthn.exe
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: latest-windows-64
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/lthn.exe


  macos-intel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno compile --unstable --allow-env --allow-run --allow-net --allow-read --allow-write --output build/lthn --target x86_64-apple-darwin src/server.ts
      - uses: actions/upload-artifact@v2
        with:
          name: macos-intel
          path: build/lthn
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: latest-macos-intel
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/lthn

  macos-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno compile --unstable --allow-env --allow-run --allow-net --allow-read --allow-write --output build/lthn --target aarch64-apple-darwin src/server.ts
      - uses: actions/upload-artifact@v2
        with:
          name: macos-m1
          path: build/lthn
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: latest-macos-arm
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/lthn
