
name: lethean-server

on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [ linux, macos-intel, macos-arm, windows ]
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.18.x
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm run server:build:${{ matrix.type }}
      - uses: papeloto/action-zip@v1
        with:
          files: build/lethean-server
          dest: ${{ matrix.type }}.zip
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.type }}
          path: ${{ matrix.type }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.type }}.zip
      - name: Release Branch
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: canary
          prerelease: true
          files: ${{ matrix.type }}.zip
